
OBJS =

EE_BIN = daedalus.elf

EE_OBJS = $(OBJS)

EE_CFLAGS = 

EE_LDFLAGS = -L$(PS2SDK)/ports/lib

all: $(EE_BIN)

clean:
	rm -f $(EE_OBJS) $(EE_BIN)

include $(PS2SDK)/samples/Makefile.pref
include $(PS2SDK)/samples/Makefile.eeglobal
