//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Script1.rc
//
#define IDS_DAEDALUS_STRING             2
#define IDS_COLUMN_NAME                 5
#define IDS_COLUMN_COUNTRY              6
#define IDS_COLUMN_SIZE                 7
#define IDS_COLUMN_COMMENTS             8
#define IDS_COLUMN_COMMENT              8
#define IDS_LOCALIZATION_DLL_FOR_VERSION 10
#define IDS_COLUMN_BOOT                 11
#define IDS_COLUMN_INFO                 12
#define IDS_CPUTHREAD_EXCEPTION         13
#define IDS_UNABLETOSTARTCPUTHREAD      15
#define IDS_NOROMLOADED                 16
#define IDS_UNABLETOINITINPUT           17
#define IDS_UNSUPPORTEDTEXFMT           18
#define IDS_NODX8                       19
#define IDS_EXCEPTION                   20
#define IDS_SELECTFOLDER                21
#define IDS_SELECTSAVEFOLDER            22
#define IDS_PLAYABLE                    23
#define IDS_ALMOSTPLAYABLE              24
#define IDS_NOTPLAYABLE                 25
#define IDS_DOESNTWORK                  26
#define IDS_STOPSTARTCPU                27
#define IDS_CONFIGGFX                   28
#define IDS_AUDIOTHREAD_EXCEPTION       29
#define IDS_COLUMN_SAVE                 30
#define IDR_APP_MENU                    101
#define IDR_APP_ACCELERATOR             102
#define IDD_ABOUT                       103
#define IDC_ROMLISTVIEW                 103
#define IDC_STATUSBAR                   104
#define IDM_COLUMN_NAME                 105
#define IDM_COLUMN_COUNTRY              106
#define IDD_INPUT                       107
#define IDM_COLUMN_SIZE                 107
#define IDD_ROMSETTINGS                 108
#define IDM_COLUMN_COMMENT              108
#define IDD_INPUTSELECT                 109
#define IDM_COLUMN_INFO                 109
#define IDD_DISCLAIMER                  110
#define IDM_COLUMN_SAVE                 110
#define IDM_COLUMN_MORE                 111
#define IDB_DAEDALUS                    112
#define IDM_COLUMN_BOOT                 112
#define IDI_DAEDALUS_ICON               113
#define IDD_SELECTDEVICE                115
#define IDD_CONFIG                      116
#define IDD_PAGE_DIRECTORIES            117
#define IDD_PAGE_DEBUG                  118
#define IDD_PAGE_SETTINGS               119
#define IDD_PAGE_PLUGINS                120
#define IDC_AUDIO_PLUGIN_COMBO          1002
#define IDC_INPUT_PLUGIN_COMBO          1003
#define IDC_CONTROLLER_COMBO            1005
#define IDC_BUTTON_LIST                 1006
#define IDC_ABOUT_GRAPHICS_BUTTON       1006
#define IDC_FIRST_MAP_COMBO             1007
#define IDC_ABOUT_AUDIO_BUTTON          1007
#define IDC_SECOND_MAP_COMBO            1008
#define IDC_ABOUT_INPUT_BUTTON          1008
#define IDC_OSHLE_CHECK                 1009
#define IDC_CHECK2                      1010
#define IDC_NAME_EDIT                   1011
#define IDC_COMMENT2_EDIT               1013
#define IDC_DISABLE_DYNAREC_CHECK       1014
#define IDC_DYNAREC_SUPPORTED_CHECK     1014
#define IDC_DISABLE_SPEEDSYNC_CHECK     1016
#define IDC_UCODE_EDIT                  1018
#define IDC_EEPROM_CHECK                1019
#define IDC_DISABLE_TEXCRC_CHECK        1020
#define IDC_RESET_BUTTON                1023
#define IDC_EXPANSIONPAK_CHECK          1023
#define IDC_FIRST_MAP_STATIC            1024
#define IDC_SECOND_MAP_STATIC           1025
#define IDC_CONFIG_COMBO                1026
#define IDC_NEW_BUTTON                  1028
#define IDC_EDIT_BUTTON                 1029
#define IDC_C1_CHECK                    1031
#define IDC_C2_CHECK                    1032
#define IDC_C3_CHECK                    1033
#define IDC_C4_CHECK                    1034
#define IDC_DAEDALUS_LOGO               1035
#define IDC_EEPROMSIZE_EDIT             1035
#define IDC_SIZE_STATIC                 1036
#define IDC_RESCAN_EDIT                 1037
#define IDC_RESCAN1_STATIC              1038
#define IDC_RESCAN2_STATIC              1039
#define IDC_COMMENT_COMBO               1041
#define IDC_ADAPTER_COMBO               1042
#define IDC_DEVICE_COMBO                1043
#define IDC_WINDOW                      1044
#define IDC_FULLSCREEN                  1045
#define IDC_FULLSCREENMODES_COMBO       1046
#define IDC_MULTISAMPLE_COMBO           1047
#define IDC_PAGE_LIST                   1048
#define IDC_DEBUG_CONSOLE_CHECK         1051
#define IDC_TRAP_EXCEPTIONS_CHECK       1052
#define IDC_ROM_DIRECTORY_LIST          1053
#define IDC_BUTTON1                     1054
#define IDC_ADD_ROMSDIR_BUTTON          1054
#define IDC_BUTTON2                     1055
#define IDC_REMOVE_ROMSDIR_BUTTON       1055
#define IDC_SAVE_DIR_EDIT               1056
#define IDC_PLUGIN_DIR_EDIT             1057
#define IDC_DUMPS_DIR_EDIT              1058
#define IDC_CHECK3                      1059
#define IDC_SELECT_SAVE_BUTTON          1060
#define IDC_BUTTON4                     1061
#define IDC_RUN_ROMS_AUTO_CHECK         1061
#define IDC_BUTTON5                     1062
#define IDC_RECURSIVE_SCAN_CHECK        1062
#define IDC_WARN_MEM_ERRORS_CHECK       1063
#define IDC_GRAPHICS_PLUGIN_COMBO       1066
#define IDC_ENABLE_AUDIO_CHECK          1067
#define IDC_LOCAL_COMBO                 1068
#define IDC_SAVETYPE_UNK_RADIO          1074
#define IDC_SAVETYPE_EEP4K_RADIO        1075
#define IDC_SAVETYPE_EEP16K_RADIO       1076
#define IDC_SAVETYPE_SRAM_RADIO         1077
#define IDC_SAVETYPE_FLASH_RADIO        1078
#define IDC_EPAK_UNKNOWN_RADIO          1079
#define IDC_EPAK_UNUSED_RADIO           1080
#define IDC_EPAK_USED_RADIO             1081
#define IDC_RADIO4                      1082
#define IDC_EPAK_REQUIRED_RADIO         1082
#define IDM_OPEN                        40001
#define IDM_EXIT                        40002
#define IDM_CPUSTART                    40006
#define IDM_CPUSTOP                     40007
#define IDM_ABOUT                       40012
#define IDM_INPUTCONFIG                 40021
#define IDM_REFRESH                     40025
#define IDM_SELECTDIR                   40026
#define IDM_SCREENSHOT                  40031
#define IDM_TOGGLEFULLSCREEN            40032
#define IDM_DAEDALUS_HOME               40034
#define IDM_LOAD                        40035
#define IDM_SAVE                        40036
#define IDM_NEWCOMBINER                 40037
#define IDM_CONFIGURATION               40038
#define IDM_GRAPHICS_CONFIG             40039
#define IDM_AUDIO_CONFIG                40041

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        118
#define _APS_NEXT_COMMAND_VALUE         40042
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
